In [1]:
!opensubtitles-download de

/home/cdminix/.cache/opensubtitles/de
Language de already downloaded.


In [1]:
from opensubtitles_dataloader import OpenSubtitlesDataset
import numpy as np

In [2]:
dataset = OpenSubtitlesDataset('de', n_sents=(5,10), first_n_lines=20_000, overwrite=True)

In [4]:
dataset[1]

'- Hallo . - Hallo . Willkommen zu Hause , Mann . Komm , setz dich und spiel uns was vor . - Wir zahlen mit Versprechen . - Die kann ein Mann nicht essen . Und nicht beim Kartenspiel verlieren . McLaine ! - Nein , das kann er nicht . - Wo warst du so lange und warum ?'

In [6]:
train, test, valid = dataset.splits(seed=42)

In [8]:
for i in range(10):
    print(test[i])

Exakt 4 Minuten . Brauchten Sie ärztliche hilfe ? - Sir ? - Ich meine wegen der Schwester . Sehr raffiniert . Warden hatte Recht . Setzen Sie sich . Ich bat Sie hierher , damit Sie den vierten Mann für Ihr Team finden . - Mr. Joyce soll reinkommen .
Und ruft Ihr Mann Sie nicht manchmal vom Büro aus an ? Das ist Erpressung . Ich werde sofort die Polizei anrufen . Genau das hat Myra Herbert auch gesagt . Getan hat sie es nicht . - Myra ? 
Ich will in Wien bleiben . Dann nehmen wir halt einen Verwalter . Einen Fremden auf dem Adlerhof ? Soll Poldi seine Laufbahn aufgeben ? Sag auch mal was ! Ja , ja . 
Ist es wieder dein Arm ? Ich weiß , dass ihr denken werdet , ich wäre verrückt , aber ich bekomme noch ein Baby . Wenn es überhaupt eine Chance haben soll , geboren zu werden , dann ... Ich meine , nachdem ich so viel Blut verloren habe und ... Und ich will dieses Baby , Papa . Mehr , als ich jemals etwas gewollt habe . 
Es ist bald so weit . Papa . - Wie funktioniert das ? - Gute alte Hexe

NameError: name 'train' is not defined

In [19]:
test[3]

('Das sind ... !\n ?\n !', 19)

In [15]:
import numpy as np

In [9]:
np.tril(np.ones((5, 5)), -1)[:, 1:-2]

array([[0., 0.],
       [0., 0.],
       [1., 0.],
       [1., 1.],
       [1., 1.]])

In [26]:
np.triu(np.ones((5, 5)), 1)[:, 2:-1]

array([[1., 1.],
       [1., 1.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

In [20]:
dataset._get_alt_lens()

array([78., 51., 49., ..., 40., 20., 40.])

In [12]:
dataset.lenghts